# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'fengzhuang' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fengzhuang
   pod 'AFNetworking','3.1.0'
   pod 'MJRefresh','3.1.0'
   pod 'MJExtension','3.0.10'
   pod 'MBProgressHUD','0.9.2'
   pod 'SDWebImage','3.7.6'
   
  target 'fengzhuangTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fengzhuangUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
